### PR TITLE
Two examples translated from W3C Ajax tutorial.

### PR DESCRIPTION
**Pull request by sbriais**
Hello,

I thought it could possibly interest some other people to have some Ajax example...

Cheers

Sébastien

### CODE REVIEW

**Comment by whitequark** [comment]
@Drup, what do you make of this? It doesn't look very ocsigen-y to me...

**Comment by sbriais** [comment]
Indeed! The purpose is to show examples using only js_of_ocaml, and not relying on Eliom/Ocsigen/...

**Comment by whitequark** [comment]
Oh, oops. I thought this was the eliom-example project! Nevermind then.

**Comment by Drup** [comment]
It's very un-ocsigen-y, indeed. But on top of it, it's very low level. You should use `XmlHttpRequest.get` (and it would replace all of your low level code) and to attach a handler to some button, use `Lwt_js_event` (instead of the ugly `Js.Unsafe.global`).

**Comment by sbriais** [comment]
Thanks for your comments! That's why some more js_of_ocaml examples are needed!

**Pull request merged**
